# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170326_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_author', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.BlogPage')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpagecomments',
            name='page',
        ),
        migrations.DeleteModel(
            name='BlogPageComments',
        ),
    ]
