# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_main_text',
            field=models.CharField(default='Dynamic Sales Ops', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_sub_text',
            field=models.CharField(default='For all your sales ops needs', max_length=250),
            preserve_default=False,
        ),
    ]
